# Dataset configuration to establish baseline
dataset_name: squad_v2
huggingface_dataset_id: squad_v2
train_split_name: train
evaluation_split_name: validation

# Full dataset
maximum_train_examples: null
maximum_evaluation_examples: null